// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdlIuBujyPu_GTlCVvkNYAWqsjiJFZiXw',
    appId: '1:964924298785:web:991ab2f56cb2a4b95ff560',
    messagingSenderId: '964924298785',
    projectId: 'web01oz',
    authDomain: 'web01oz.firebaseapp.com',
    storageBucket: 'web01oz.firebasestorage.app',
    measurementId: 'G-SXDXTGZFF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYfHD5TVwzW0ijPHp1eD92kpoyJLse-60',
    appId: '1:964924298785:android:e0218667cf53c9f35ff560',
    messagingSenderId: '964924298785',
    projectId: 'web01oz',
    storageBucket: 'web01oz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWUSlBvmiIKekzeOEPUk_SjiTAJnuJpdI',
    appId: '1:964924298785:ios:eff2b4c0e30129b45ff560',
    messagingSenderId: '964924298785',
    projectId: 'web01oz',
    storageBucket: 'web01oz.firebasestorage.app',
    iosBundleId: 'com.example.web01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWUSlBvmiIKekzeOEPUk_SjiTAJnuJpdI',
    appId: '1:964924298785:ios:eff2b4c0e30129b45ff560',
    messagingSenderId: '964924298785',
    projectId: 'web01oz',
    storageBucket: 'web01oz.firebasestorage.app',
    iosBundleId: 'com.example.web01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdlIuBujyPu_GTlCVvkNYAWqsjiJFZiXw',
    appId: '1:964924298785:web:08d8bcf4a4e174585ff560',
    messagingSenderId: '964924298785',
    projectId: 'web01oz',
    authDomain: 'web01oz.firebaseapp.com',
    storageBucket: 'web01oz.firebasestorage.app',
    measurementId: 'G-TBXR0WJ1GN',
  );

}